name: Android CI (无签名版)

on:
  workflow_dispatch:  # 手动触发
  push:
    tags:
      - '*'  # 标签推送触发

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: '18'
      JAVA_VERSION: '17'
      ANDROID_BUILD_TOOLS: '34.0.0'
      ANDROID_PLATFORM: '34'
      GRADLE_OPTS: '-Dorg.gradle.caching=true -Dorg.gradle.parallel=false -Dorg.gradle.daemon=true -Dorg.gradle.workers.max=2 --scan'

    steps:
      # 1. 检出代码
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          path: .

      # 2. 设置Node.js环境
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      # 3. 安装npm依赖
      - name: Install dependencies
        run: |
          npm ci
          npx react-native config

      # 4. 设置Java环境
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: gradle

      # 5. 设置Android环境
      - uses: android-actions/setup-android@v3
        with:
          build-tools-version: ${{ env.ANDROID_BUILD_TOOLS }}
          platform-version: ${{ env.ANDROID_PLATFORM }}
          ndk-version: "25.2.9519653"

      # 6. 构建APK
      - name: Build Release APK
        working-directory: ./android
        run: |
          # 设置权限
          chmod +x gradlew
          
          # 构建（启用缓存和并行）
          ./gradlew assembleRelease \
            --build-cache \
            --no-parallel \
            --scan \
            --stacktrace \
            --info \
            -PreactNativeArchitectures=arm64-v8a,x86_64

          # 验证构建结果
          if [ ! -f "app/build/outputs/apk/release/app-release-unsigned.apk" ]; then
            echo "::error::APK file not found!"
            find . -name "*.log" -type f -print -exec cat {} \;
            exit 1
          fi

      # 7. 上传APK工件
      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
          retention-days: 7